"""initial schema

Revision ID: 62cca6f53ae0
Revises: 
Create Date: 2026-07-23 22:43:19.364433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cca6f53ae0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=False),
    sa.Column('mesh_id', sa.String(length=32), nullable=True),
    sa.Column('therapeutic_area', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=256), nullable=False),
    sa.Column('name_zh', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pmid', sa.String(length=32), nullable=True),
    sa.Column('doi', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('retracted', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('pmid')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_path', sa.String(length=512), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', 'content_hash', name='uq_source_doc_url_hash')
    )
    op.create_table('targets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('gene', sa.String(length=32), nullable=True),
    sa.Column('pathway', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('inn', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('modality', sa.String(length=128), nullable=True),
    sa.Column('mechanism', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.Enum('DAILY', 'WEEKLY', name='reporttype', native_enum=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.Enum('TRIAL_CHANGE', 'CLINICAL_RESULT', 'REGULATORY', 'PUBLICATION', 'DEAL', 'CONGRESS', name='eventtype', native_enum=False), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('indication_id', sa.String(length=32), nullable=True),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('result_direction', sa.Enum('POSITIVE', 'NEGATIVE', 'MIXED', 'INCONCLUSIVE', 'NA', name='resultdirection', native_enum=False), nullable=True),
    sa.Column('phase', sa.Enum('PRECLINICAL', 'PHASE_1', 'PHASE_1_2', 'PHASE_2', 'PHASE_2_3', 'PHASE_3', 'PHASE_4', 'NA', name='phase', native_enum=False), nullable=True),
    sa.Column('significance_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('medical_review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_INFO', name='medicalreviewstatus', native_enum=False), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('related_event_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nct_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('overall_status', sa.String(length=64), nullable=True),
    sa.Column('phase', sa.Enum('PRECLINICAL', 'PHASE_1', 'PHASE_1_2', 'PHASE_2', 'PHASE_2_3', 'PHASE_3', 'PHASE_4', 'NA', name='phase', native_enum=False), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('primary_completion_date', sa.Date(), nullable=True),
    sa.Column('study_completion_date', sa.Date(), nullable=True),
    sa.Column('outcome_measures', sa.Text(), nullable=True),
    sa.Column('results_posted', sa.Boolean(), nullable=False),
    sa.Column('sponsor_org_id', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('indication_id', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_snapshot_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.id'], ),
    sa.ForeignKeyConstraint(['sponsor_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nct_id')
    )
    op.create_table('evidences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('source_document_id', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('evidence_level', sa.Enum('A', 'B', 'C', 'D', 'E', name='evidencelevel', native_enum=False), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trial_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('watch_fields_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_snapshots')
    op.drop_table('evidences')
    op.drop_table('trials')
    op.drop_table('events')
    op.drop_table('reports')
    op.drop_table('assets')
    op.drop_table('targets')
    op.drop_table('source_documents')
    op.drop_table('publications')
    op.drop_table('organizations')
    op.drop_table('indications')
    op.drop_table('conferences')
    # ### end Alembic commands ###
